#!/bin/sh

JAR=/usr/local/network-ps/pscan.jar

if [ ! -x "$(which java)" ]; then
    echo "fatal: cannot find the java application launcher"
    exit 1
fi

if [ ! -f "$JAR" ]; then
    echo "fatal: cannot find $JAR"
    exit 1
fi

exec java -jar "$JAR" || exit 1

# not reached
exit 0
